### ISSUE TITLE
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace

### ISSUE THREAD

**Issue by poiedk** [app-generator/django-dashboard-adminlte#2]
I think double entry must be deleted on **/django-dashboard-adminlte/core/urls.py**

`urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path('admin' , admin.site.urls),          # Django admin route 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))             # UI Kits Html files
]`

**Comment by app-generator** [comment]
Hello @poiedk, 

Please update. 
Issue patched in [v1.0.1](https://github.com/app-generator/django-dashboard-adminlte/releases)
